--ADVANCE ACCESS DASHBOARDS - Straight Clarity Pull

--Detailed Pulled
SELECT DISTINCT 
ENC.PAT_ID,
CAST(ENC.CONTACT_DATE as DATE),
DEP.DEPARTMENT_NAME,
SER.PROV_NAME as VISIT_PROV_NAME,
DEP2.SPECIALTY as PROV_DEP_SPEC,
ZCEnc.NAME as ENC_TYPE,
ZCAppStat.NAME as APP_STATUS,
PATIENT.PAT_MRN_ID,
PATIENT.PAT_FIRST_NAME,
PATIENT.PAT_LAST_NAME

FROM
PAT_ENC ENC
Left Join CLARITY_DEP DEP on ENC.DEPARTMENT_ID=DEP.DEPARTMENT_ID
Left Join CLARITY_PRC PRC on ENC.APPT_PRC_ID=PRC.PRC_ID
Left Join PATIENT on PATIENT.PAT_ID=ENC.PAT_ID
Left Join CLARITY_SER SER on SER.PROV_ID=ENC.VISIT_PROV_ID
Left Join CLARITY_SER_DEPT SER_DEP on SER.PROV_ID=SER_DEP.PROV_ID
Left Join CLARITY_DEP DEP2 on DEP2.DEPARTMENT_ID=SER_DEP.DEPARTMENT_ID
Left Join ZC_DISP_ENC_TYPE ZCEnc on ZCEnc.DISP_ENC_TYPE_C=ENC.ENC_TYPE_C
Left Join ZC_APPT_STATUS ZCAppStat on ZCAppStat.APPT_STATUS_C=ENC.APPT_STATUS_C

WHERE
CAST(ENC.CONTACT_DATE as DATE)  between '2013-12-02' and  '2013-12-02'
and VISIT_PROV_NAME like  '%CHESS, ERIC%' 
and ENC_TYPE not in ('ERROR','APPOINTMENT')
and ENC.APPT_STATUS_C is not null
and ZCAppStat.NAME <>'No Show'
and PROV_DEP_SPEC in ('Family Practice', 'Internal Medicine', 'Pediatrics')
and ENC.PAT_ID not in (select distinct pat_id from hcclco.patient_type where patient_type_c = 1214);


--Daily Encounter Counts
SELECT DISTINCT 
CAST(ENC.CONTACT_DATE as DATE),
SER.PROV_NAME as VISIT_PROV_NAME,
ZCEnc.NAME as ENC_TYPE,
ZCAppStat.NAME as APP_STATUS,
COUNT(ENC.PAT_ID) as COUNT_OF_PATIENT

FROM
PAT_ENC ENC
Left Join CLARITY_DEP DEP on ENC.DEPARTMENT_ID=DEP.DEPARTMENT_ID
Left Join CLARITY_PRC PRC on ENC.APPT_PRC_ID=PRC.PRC_ID
Left Join PATIENT on PATIENT.PAT_ID=ENC.PAT_ID
Left Join CLARITY_SER SER on SER.PROV_ID=ENC.VISIT_PROV_ID
Left Join CLARITY_SER_DEPT SER_DEP on SER.PROV_ID=SER_DEP.PROV_ID
Left Join CLARITY_DEP DEP2 on DEP2.DEPARTMENT_ID=SER_DEP.DEPARTMENT_ID
Left Join ZC_DISP_ENC_TYPE ZCEnc on ZCEnc.DISP_ENC_TYPE_C=ENC.ENC_TYPE_C
Left Join ZC_APPT_STATUS ZCAppStat on ZCAppStat.APPT_STATUS_C=ENC.APPT_STATUS_C

WHERE
CAST(ENC.CONTACT_DATE as DATE)  between '2013-12-02' and  '2013-12-02'
and VISIT_PROV_NAME like  '%CHESS, ERIC%' 
and ENC_TYPE not in ('ERROR','APPOINTMENT')
and ENC.APPT_STATUS_C is not null
and ZCAppStat.NAME <>'No Show'
and DEP2.SPECIALTY in ('Family Practice', 'Internal Medicine', 'Pediatrics')
and ENC.PAT_ID not in (select distinct pat_id from hcclco.patient_type where patient_type_c = 1214)

GROUP BY (1,2,3,4)