SELECT AVA.DEPARTMENT_ID,
AVA.DEPARTMENT_NAME,
AVA.PROV_ID, 
AVA.PROV_NAME, 
AVA.SLOT_BEGIN_TIME, 
AVA.SLOT_LENGTH,
PATIENT.PAT_MRN_ID,
PATIENT.PAT_NAME,
CAST(AVA.AGE as VARCHAR(2)),
AVA.PAT_ENC_CSN_ID,
AVA.ENC_TYPE,
AVA.PRC_NAME,
AVA.APPT_STATUS,
DAT.MONTH_NAME,
DAT."YEAR",
DAT.QUARTER_NUMBER
FROM PATIENT 
Inner Join (Select AVAILABILITY.DEPARTMENT_ID, DEPARTMENT_NAME, AVAILABILITY.PROV_ID, PAT_ENC.PAT_ENC_CSN_ID, PROV_NAME, PAT_ENC.PAT_ID, PAT_ENC.CONTACT_DATE, CLARITY_PRC.PRC_NAME, 
					SLOT_BEGIN_TIME, APPT_NUMBER, AVAILABILITY.APPT_PRC_ID, AVAILABILITY.APPT_BLOCK_C, SLOT_LENGTH, PAT_ENC.AGE, ZC_DISP_ENC_TYPE.NAME as ENC_TYPE, ZC_APPT_STATUS.NAME as APPT_STATUS
			From AVAILABILITY 
			Left Outer Join ZC_APPT_BLOCK 
			on AVAILABILITY.APPT_BLOCK_C=ZC_APPT_BLOCK.APPT_BLOCK_C
			Left Join CLARITY_DEP 
			on CLARITY_DEP.DEPARTMENT_ID=AVAILABILITY.DEPARTMENT_ID
			Left Join CLARITY_SER
			on CLARITY_SER.PROV_ID=AVAILABILITY.PROV_ID
			Left Join CLARITY_PRC
			on CLARITY_PRC.PRC_ID=AVAILABILITY.APPT_PRC_ID
			Left Join PAT_ENC 
			on PAT_ENC.PAT_ENC_CSN_ID=AVAILABILITY.PAT_ENC_CSN_ID
			Inner Join ZC_DISP_ENC_TYPE 
			on ZC_DISP_ENC_TYPE.DISP_ENC_TYPE_C=ENC_TYPE_C
			Left Join ZC_APPT_STATUS
			on ZC_APPT_STATUS.APPT_STATUS_C=PAT_ENC.APPT_STATUS_C
			Where APPT_NUMBER<>'0') as AVA --Appointments 
			on PATIENT.PAT_ID=AVA.PAT_ID
Inner Join DATE_DIMENSION DAT on DAT.CALENDAR_DT=AVA.CONTACT_DATE
WHERE CAST(AVA.SLOT_BEGIN_TIME as DATE)>'2013-12-01'
And AVA.DEPARTMENT_NAME  in ('OBGY LAKE','OBGY SOUT')
ORDER BY AVA.SLOT_BEGIN_TIME ASC;

