SELECT
APPT.PAT_ID, 
PATIENT.PAT_MRN_ID,
PATIENT.PAT_NAME,
APPT.CONTACT_DATE,
ZSTAT.NAME as APPT_STATUS, 
APPT.PROV_ID, 
ZTYPE."TITLE" as ENCOUNTER_TYPE,
PRC.PRC_NAME as VISIT_TYPE, 
SER.PROV_NAME,
SER.PROV_ABBR, 
DEP.DEPARTMENT_ID,
DEP.DEPARTMENT_NAME

FROM 
PAT_ENC_APPT APPT
Inner Join PAT_ENC PAT on APPT.PAT_ENC_CSN_ID=PAT.PAT_ENC_CSN_ID
Left Join CLARITY_PRC PRC on PRC.PRC_ID=PAT.APPT_PRC_ID
Inner Join CLARITY_SER SER on SER.PROV_ID=APPT.PROV_ID
Inner Join CLARITY_DEP DEP on DEP.DEPARTMENT_ID=APPT.DEPARTMENT_ID
Left Join ZC_DISP_ENC_TYPE ZTYPE on PAT.ENC_TYPE_C=ZTYPE.DISP_ENC_TYPE_C
Inner Join PATIENT on PATIENT.PAT_ID=PAT.PAT_ID
Inner Join ZC_APPT_STATUS ZSTAT on ZSTAT.APPT_STATUS_C=PAT.APPT_STATUS_C

WHERE
PAT.ENC_TYPE_C='50'
and PROV_ABBR like '%MAMMO COACH%' 
and PRC.PRC_NAME like '%MAMMOGRAM%'
and PAT.APPT_STATUS_C = '2'
and PAT.PAT_ID not in (Select Distinct PAT_ID 
										From PATIENT_TYPE
										Where PATIENT_TYPE_C ='1214')
										
ORDER BY
APPT.CONTACT_DATE desc


