Select 
PAT_ENC.PAT_ENC_CSN_ID,
IDENTITY_ID.IDENTITY_ID as PAT_MRN,
PAT_ENC.CONTACT_DATE,
PAT_ENC.ENC_TYPE_TITLE,
PAT_ENC.APPT_LENGTH,
CLARITY_PRC.PRC_NAME as VISIT_TYPE,
CLARITY_DEP.DEPARTMENT_NAME,
CLARITY_SER.PROV_NAME,
CLARITY_SER.CLINICIAN_TITLE,
PAT_ENC.CHECKIN_TIME,
PAT_ENC.CHECKOUT_TIME,
PAT_ENC.COPAY_COLLECTED,
ZCA.NAME as APPT_STATUS

From PAT_ENC
Left Join IDENTITY_ID  on IDENTITY_ID.PAT_ID=PAT_ENC.PAT_ID
Left Join CLARITY_DEP on PAT_ENC.DEPARTMENT_ID=CLARITY_DEP.DEPARTMENT_ID
Left Join CLARITY_SER on PAT_ENC.VISIT_PROV_ID=CLARITY_SER.PROV_ID
Left Join ZC_APPT_STATUS ZCA on PAT_ENC.APPT_STATUS_C=ZCA.APPT_STATUS_C
Left Join CLARITY_PRC on PAT_ENC.APPT_PRC_ID=CLARITY_PRC.PRC_ID

Where PAT_ENC.ENC_TYPE_TITLE='APPOINTMENT'
And PAT_ENC.CHECKIN_TIME is not null
And PAT_ENC.CHECKOUT_TIME is null
And PAT_ENC.CONTACT_DATE >date'2013-11-01'
And PAT_ENC.CONTACT_DATE <date'2013-11-20'
--And ZCA.NAME='Completed'
And CLARITY_SER.CLINICIAN_TITLE not in ('Clinical Nurse Specialist','MEDICAL DOCTOR','REGISTERED NURSE', 'OSTEOPATHIC DOCTOR','Student/Intern','NURSE PRACTITIONER'  )
And CLARITY_DEP.DEPARTMENT_NAME in 
('CD EXEC',
'CD HLAK',
'CD REG',
'CD RDG',
'EATING DISORDERS HLAK',
'EATING DISORDERS REG',
'EATING DISORDERS RDG',
'MH EXEC',
'MH HLAK',
'MH REG',
'MH RDG',
'BMS ACP',
'BMS ARAP',
'BMS BASE',
'BMS EAST',
'BMS ENGL',
'BMS FCO',
'BMS HLAK',
'BMS HRCH',
'BMS KCM',
'BMS LAKE',
'BMS LONG',
'BMS LVE',
'BMS RKCK',
'BMS SKY',
'BMS SMOK',
'BMS SOUT',
'BMS TON',
'BMS WEST',
'BMS WHEA');

