Select 
LOC.LOC_NAME, 
DEP.DEPARTMENT_NAME, 
HSP.CONTACT_DATE,
PATIENT.PAT_NAME,
PATIENT.PAT_MRN_ID, 
HSP.PAT_ENC_CSN_ID,
EPP.PRODUCT_TYPE,
FC.FINANCIAL_CLASS_NAME, 
TX.TX_ID as PAYMENT_CID, 
EAP.PROC_NAME as PAYMENT_TYPE, 
ENC.COPAY_DUE,
TX.AMOUNT as PAYMENT,
TX.OUTSTANDING_AMT

From PAT_ENC_HSP HSP
Inner Join CLARITY_DEP DEP on HSP.DEPARTMENT_ID=DEP.DEPARTMENT_ID
Inner Join CLARITY_LOC LOC on DEP.REV_LOC_ID=LOC.LOC_ID
Inner Join PATIENT on HSP.PAT_ID=PATIENT.PAT_ID and PAT_NAME not like 'ZZ%'
Left Join (Select *
				From ARPB_TRANSACTIONS 
				Where TX_TYPE_C='2'
				And VOID_DATE is null) as TX 
			On TX.PAT_ENC_CSN_ID=HSP.PAT_ENC_CSN_ID
Left Join CLARITY_EAP EAP on TX.CPT_CODE=EAP.PROC_CODE
Left Join CLARITY_EPP EPP on PATIENT.PRIM_EPP_ID=EPP.BENEFIT_PLAN_ID
Left Join CLARITY_FC FC on PATIENT.PRIM_FC=FC.FINANCIAL_CLASS
Left Join PAT_ENC ENC on HSP.PAT_ENC_CSN_ID=ENC.PAT_ENC_CSN_ID

Where HSP.DEPARTMENT_ID='1201000160004'
And HSP.PAT_ID not in (Select Distinct PAT_ID From PATIENT_TYPE Where PATIENT_TYPE_C='1214') --Test Patient Elimination
