Select Distinct CURRENT_COVERAGE.PAT_ID
From(
Select 
		COVERAGE_ID,
		MEM_LIST.PAT_ID, 
		LINE,
		MEM_EFF_FROM_DATE, 
		MEM_EFF_TO_DATE, 
		MEM_COVERED_YN, 
		ZC.NAME as MEM_REL_TO_SUB, 
		ZC2.NAME as MEM_TERM_REASON,
		ZC3.NAME as PATIENT_STATUS
		From COVERAGE_MEM_LIST MEM_LIST
		Left Join ZC_MEM_REL_TO_SUB ZC on MEM_LIST.MEM_REL_TO_SUB_C=ZC.MEM_REL_TO_SUB_C
		Left Join ZC_MEM_TERM_REASON ZC2 on MEM_LIST.MEM_TERM_REASON_C=ZC2.MEM_TERM_REASON_C
		Inner Join PATIENT on PATIENT.PAT_ID=MEM_LIST.PAT_ID
		Left Join ZC_PATIENT_STATUS ZC3 on PATIENT.PAT_STATUS_C=ZC3.PATIENT_STATUS_C
		Where MEM_LIST.MEM_EFF_FROM_DATE<= CURRENT_DATE --MEMBERSHIP EFFECTIVE DATE LESS THAN OR EQUAL TO TODAY
		And ((MEM_LIST.MEM_EFF_TO_DATE is null)
			or (MEM_LIST.MEM_EFF_TO_DATE > CURRENT_DATE)) --MEMBERSHIP END DATE IS NULL OR GREATER THAN CURRENT DATE
		And MEM_LIST.MEM_COVERED_YN='Y' --MEMBER IS COVERED
		And MEM_LIST.PAT_ID not in (Select PAT_ID From PATIENT_TYPE Where PATIENT_TYPE_C='1214') --MEMBER IS NOT A TEST PATIENT
		And ZC3.NAME ='Alive' --ONLY ALIVE PATIENTS
	) as CURRENT_COVERAGE

--Look back period: 3 years
--Only Kaiser Patients  (active managed care coverage) (Allison to send) 