Select 
ENC.ENC_TYPE_ID,
ENC.ENC_TYPE_NAME,
ENC.LAST_CONTACT_DATE,
DEP.DEPARTMENT_NAME as LAST_USED_DEPARTMENT,
ENC.MAX_PAT_ENC_CSN_ID,
ENC.COUNT_OF_ENCOUNTERS
From(
	Select 
			PAT_ENC.ENC_TYPE_C as ENC_TYPE_ID,
			ZC.NAME as ENC_TYPE_NAME, 
			MAX(CONTACT_DATE) as LAST_CONTACT_DATE,
			MAX(PAT_ENC_CSN_ID) as MAX_PAT_ENC_CSN_ID,
			COUNT(PAT_ENC.PAT_ENC_CSN_ID) as COUNT_OF_ENCOUNTERS
	From PAT_ENC
	Inner Join ZC_DISP_ENC_TYPE ZC on PAT_ENC.ENC_TYPE_C=ZC.DISP_ENC_TYPE_C
	Where PAT_ENC.PAT_ID not in (Select Distinct PAT_ID From PATIENT_TYPE Where PATIENT_TYPE_C='1214') --Test Patient Elimination
	Group By (1,2)) as ENC
Left Join(
	Select PAT_ENC_CSN_ID, DEPARTMENT_NAME
	From PAT_ENC
	Inner Join CLARITY_DEP on PAT_ENC.DEPARTMENT_ID=CLARITY_DEP.DEPARTMENT_ID) as DEP
	On ENC.MAX_PAT_ENC_CSN_ID=DEP.PAT_ENC_CSN_ID