Select Distinct
IDENTITY_ID.PAT_ID,
IDENTITY_ID.IDENTITY_ID as MRN,
IMM_ADMIN.DOCUMENT_ID as IMM_ADMIN_DXR_DOTONE,
TRIM(CAST('' as NUMERIC)) as IMMUNE_LPL_DOTONE,
CI.NAME as IMMUNE_NAME,
IMM_ADMIN.LINE,
IMM_DATE,
IMM_STATUS_C

From IMM_ADMIN
Inner Join DOCS_RCVD on IMM_ADMIN.DOCUMENT_ID=DOCS_RCVD.DOCUMENT_ID
Inner Join IDENTITY_ID on DOCS_RCVD.PAT_ID=IDENTITY_ID.PAT_ID
Inner Join CLARITY_IMMUNZATN CI on CI.IMMUNZATN_ID=IMM_ADMIN.IMM_TYPE_ID

UNION ALL 

Select Distinct
IDENTITY_ID.PAT_ID,
IDENTITY_ID.IDENTITY_ID as MRN,
TRIM(CAST('' as NUMERIC)) as IMM_ADMIN_DXR_DOTONE, 
IMMUNE.IMMUNE_ID as IMMUNE_LPL_DOTONE,
CL.NAME as IMMUNE_NAME,
TRIM(CAST('' as NUMERIC)) as LINE,
IMMUNE.IMMUNE_DATE as IMM_DATE,
IMMUNE.IMMNZTN_STATUS_C as IMM_STATUS_C

From IMMUNE 
Inner Join IDENTITY_ID ID on ID.PAT_ID=IMMUNE.PAT_ID
Inner Join CLARITY_IMMUNZATN CL on CL.IMMUNZATN_ID=IMMUNE.IMMUNZATN_ID