Select 
PATIENT.PAT_MRN_ID as HRN,
PAT_ENC.CONTACT_DATE as VISIT_DATE,
PAT_ENC.ENC_CLOSE_DATE,
PAT_ENC.PAT_ENC_CSN_ID,
DEP.DEPARTMENT_NAME,
RSN.ENC_REASON_NAME,
PRC.PRC_NAME as VISIT_TYPE,
SER.PROV_NAME as VISIT_PROV,
PAT_ENC.ENC_TYPE_TITLE, 
MEDS_LAST_REV_TM,
EMP.NAME as MEDS_LAST_REVIEWED_BY,
RV_HX.MEDS_HX_REV_INSTANT,
EMP2.NAME as MEDS_HX_REVIEWED_BY

From PAT_ENC
Inner Join PATIENT on PAT_ENC.PAT_ID=PATIENT.PAT_ID
Left Join CLARITY_PRC PRC on PAT_ENC.APPT_PRC_ID=PRC.PRC_ID
Left Join CLARITY_SER SER on PAT_ENC.VISIT_PROV_ID=SER.PROV_ID
Left Join CLARITY_EMP EMP on PATIENT.MEDS_LST_REV_USR_ID=EMP.USER_ID
Inner Join CLARITY_DEP DEP on PAT_ENC.DEPARTMENT_ID=DEP.DEPARTMENT_ID
Left Join MEDS_REV_HX RV_HX on PAT_ENC.PAT_ENC_CSN_ID=RV_HX.MEDS_HX_REV_CSN 
Left Join CLARITY_EMP EMP2 on MEDS_HX_REV_USER_ID=EMP2.USER_ID
Left Join CLARITY_DEP DEP2 on EMP2.LGIN_DEPARTMENT_ID = DEP2.DEPARTMENT_ID 
Left Join PAT_ENC_RSN_VISIT RSN on PAT_ENC.PAT_ENC_CSN_ID=RSN.PAT_ENC_CSN_ID
Where 
DEP.SPECIALTY='CARDIOLOGY'
And PAT_ENC.ENC_CLOSE_DATE Between DATE'2014-05-01' and DATE'2014-05-30'
And PAT_ENC.ENC_TYPE_TITLE ='TELEPHONE'
And ENC_REASON_NAME ='HOSPITAL FOLLOW UP'
