Select
COUNT(PAT.PAT_ID) as NUM_OF_PATIENTS,
ZC.NAME as PAT_MYC_STATUS,
LOC.LOC_NAME as PAT_PCP_PRIM_LOC,
ZC2.NAME as PATIENT_LIVING_STATUS,
CASE When ENC_PAT.PAT_ID is not null then 'Yes' 
	Else 'No' END as HAS_PT_HAD_ENC_IN_180
From PATIENT PAT
Inner Join PATIENT_MYC MYC on PAT.PAT_ID=MYC.PAT_ID 
Left Join ZC_MYCHART_STATUS ZC on MYC.MYCHART_STATUS_C=ZC.MYCHART_STATUS_C
Left Join ZC_PATIENT_STATUS ZC2 on PAT.PAT_STATUS_C=ZC2.PATIENT_STATUS_C
Inner Join PAT_PCP PCP on PAT.PAT_ID=PCP.PAT_ID
Inner Join CLARITY_SER_DEPT SER_DEPT on PCP.PCP_PROV_ID=SER_DEPT.PROV_ID
				And SER_DEPT.LINE='1' --Primary Department 
Inner Join CLARITY_DEP DEP on SER_DEPT.DEPARTMENT_ID=DEP.DEPARTMENT_ID
Inner Join CLARITY_LOC LOC on DEP.REV_LOC_ID=LOC.LOC_ID
Left  Join (
				Select Distinct 
				ENC.PAT_ID
				From PAT_ENC ENC
				Where ENC.CONTACT_DATE >= CURRENT_DATE-180) --Patient who have had an enc in the last 180 days
			as ENC_PAT on ENC_PAT.PAT_ID=PAT.PAT_ID
Where MYC.MYCHART_STATUS_C in any ('1','3','6') --MYC Status is activiited 
And CURRENT_DATE >= PCP.EFF_DATE
And (CURRENT_DATE < TERM_DATE or TERM_DATE is null) --PCP is active
And PCP.PCP_TYPE_C='1' --General PCP 
Group By 2,3,4,5