Select 
PAT_ENC.PAT_ENC_CSN_ID,
PAT_ENC.PAT_ID,
IDENTITY_ID.IDENTITY_ID as PAT_MRN,
PAT_ENC.CONTACT_DATE,
PAT_ENC.ENC_TYPE_TITLE,
PAT_ENC.APPT_LENGTH,
CLARITY_PRC.PRC_NAME as VISIT_TYPE,
CLARITY_DEP.DEPARTMENT_NAME,
CLARITY_SER.PROV_NAME,
CLARITY_SER.CLINICIAN_TITLE,
PAT_ENC.CHECKIN_TIME,
PAT_ENC.CHECKOUT_TIME,
PAT_ENC.COPAY_DUE,
PAT_ENC.COPAY_COLLECTED,
CASE When PAT_ENC_4.COPAY_COLL_FLAG_YN is null and PAT_ENC.COPAY_COLLECTED='0.00' then 'COPAY ZERO'
			Else PAT_ENC_4.COPAY_COLL_FLAG_YN END as COPAY_FLAG,
ZCA.NAME as APPT_STATUS

From PAT_ENC
Left Join IDENTITY_ID  on IDENTITY_ID.PAT_ID=PAT_ENC.PAT_ID
Left Join CLARITY_DEP on PAT_ENC.DEPARTMENT_ID=CLARITY_DEP.DEPARTMENT_ID
Left Join CLARITY_SER on PAT_ENC.VISIT_PROV_ID=CLARITY_SER.PROV_ID
Left Join ZC_APPT_STATUS ZCA on PAT_ENC.APPT_STATUS_C=ZCA.APPT_STATUS_C
Left Join CLARITY_PRC on PAT_ENC.APPT_PRC_ID=CLARITY_PRC.PRC_ID
Inner Join PAT_ENC_4 on PAT_ENC.PAT_ENC_CSN_ID=PAT_ENC_4.PAT_ENC_CSN_ID

Where 
(PAT_ENC.ENC_TYPE_TITLE='APPOINTMENT'
And PAT_ENC.CHECKIN_TIME is not null
And PAT_ENC.CHECKOUT_TIME is null
And (PAT_ENC.COPAY_COLLECTED=PAT_ENC.COPAY_DUE or (PAT_ENC.COPAY_DUE>'0.00' and PAT_ENC.COPAY_COLLECTED>'0.00'))
And COPAY_FLAG <>'N'
And CLARITY_SER.CLINICIAN_TITLE is not null 
And CLARITY_PRC.PRC_NAME <> 'TELEPHONE VISIT'
And PAT_ENC.CONTACT_DATE >date'2013-11-01'
And PAT_ENC.CONTACT_DATE <date'2013-11-30')
Or
(PAT_ENC.CHECKIN_TIME is not null
And PAT_ENC.CHECKOUT_TIME is null
And (PAT_ENC.COPAY_COLLECTED=PAT_ENC.COPAY_DUE or (PAT_ENC.COPAY_DUE>'0.00' and PAT_ENC.COPAY_COLLECTED>'0.00'))
And COPAY_FLAG <>'N'
And CLARITY_SER.CLINICIAN_TITLE is not null 
And CLARITY_PRC.PRC_NAME <> 'TELEPHONE VISIT'
And PAT_ENC.CONTACT_DATE >date'2013-11-01'
And PAT_ENC.CONTACT_DATE <date'2013-11-30'
And ZCA.NAME= 'LEFT WITHOUT SEEN')


