--IVR Patients
SELECT DISTINCT
QFQ.FORM_ID, 
QQ.QUEST_ID, 
QQ.QUEST_NAME, 
PAT.PAT_MRN_ID, 
PAT.PAT_ID, 
PAT.PAT_NAME, 
Q2.QUESTION as QUESTION_1,
Q2.QUEST_ANSWER as QUESTION_1_ANSWER,
QOVTM.QUESTION as QUESTION_2, 
PAT.QUEST_ANSWER as QUESTION_2_ANSWER, 
PAT.CONTACT_DATE

FROM
CL_QQUEST QQ
Left Join CL_QQUEST_OVTM QOVTM on QOVTM.QUEST_ID=QQ.QUEST_ID
Left Join CL_QFORM_QUEST QFQ on QFQ.QUEST_ID=QQ.QUEST_ID
Left Join CL_QQUEST_QFRESP QF on QF.QUESTION_ID=QQ.QUEST_ID
Inner Join (Select PAT_ENC_QUESR.CONTACT_DATE, PATIENT.PAT_ID, PATIENT.PAT_NAME, PATIENT.BIRTH_DATE, PATIENT.SEX, PATIENT.PAT_MRN_ID, PAT_ENC_QUESR.QUEST_ID, PAT_ENC_QUESR.QUEST_DATE, PAT_ENC_QUESR.QUEST_ANSWER
     From PATIENT 
     Inner Join PAT_ENC_QUESR
     on PAT_ENC_QUESR.PAT_ID=PATIENT.PAT_ID) as PAT on PAT.QUEST_ID=QQ.QUEST_ID
Inner Join (Select Distinct
		QFQ.FORM_ID, 
		QQ.QUEST_ID, 
		QQ.QUEST_NAME, 
		PAT.PAT_MRN_ID, 
		PAT.PAT_ID, 
		PAT.PAT_NAME, 
		QOVTM.QUESTION, 
		PAT.QUEST_ANSWER, 
		PAT.CONTACT_DATE
		From CL_QQUEST QQ
		Left Join CL_QQUEST_OVTM QOVTM on QOVTM.QUEST_ID=QQ.QUEST_ID
		Left Join CL_QFORM_QUEST QFQ on QFQ.QUEST_ID=QQ.QUEST_ID
		Left Join CL_QQUEST_QFRESP QF on QF.QUESTION_ID=QQ.QUEST_ID
		Inner Join (Select PAT_ENC_QUESR.CONTACT_DATE, PATIENT.PAT_ID, PATIENT.PAT_NAME, PATIENT.BIRTH_DATE, PATIENT.SEX, PATIENT.PAT_MRN_ID, PAT_ENC_QUESR.QUEST_ID, PAT_ENC_QUESR.QUEST_DATE, PAT_ENC_QUESR.QUEST_ANSWER
		     From PATIENT 
		     Inner Join PAT_ENC_QUESR
		     on PAT_ENC_QUESR.PAT_ID=PATIENT.PAT_ID) as PAT on PAT.QUEST_ID=QQ.QUEST_ID
		Where QFQ.FORM_ID= '121100383'
		And QQ.QUEST_ID in any ('12177402')
		And PAT.QUEST_ANSWER=  'A) Services Accepted'
		And QOVTM.Contact_Date=(Select Max(Contact_Date) as Contact_Date
		            From CL_QQUEST_OVTM OVTM
		            Where OVTM.Quest_ID=QOVTM.Quest_ID)
		Group By (1,2,3,4,5,6,7,8,9)) as Q2 on PAT.PAT_MRN_ID=Q2.PAT_MRN_ID
																and PAT.CONTACT_DATE=Q2.CONTACT_DATE --QUESTION 1 SUBQUERY
WHERE
QFQ.FORM_ID= '121100383'
And QQ.QUEST_ID in any ('12177407')
And PAT.QUEST_ANSWER in any ( 'A) Initial','''B) Ongoing','C) Annual','D) Transitions'  )
And QOVTM.Contact_Date=(Select Max(Contact_Date) as Contact_Date
            From CL_QQUEST_OVTM OVTM
            Where OVTM.Quest_ID=QOVTM.Quest_ID)
And PAT.CONTACT_DATE between  {d '2014-01-01'}  and  {d '2014-01-31'} 
Group By (1,2,3,4,5,6,7,8,9,10,11)
Order By PAT.PAT_MRN_ID;
