Select Distinct
ENC.PAT_ENC_CSN_ID,
ENC.PAT_ID, 
PATIENT.PAT_MRN_ID,
ZCEnc.NAME as ECOUNTER_TYPE,
DEP.DEPARTMENT_NAME,
ENC.CONTACT_DATE as ENCOUNTER_DATE,  
WOUND.REF_TYPE,
WOUND.DESCRIPTION as WOUND_CARE_REFERRAL,
IMAGE.ORDER_TYPE as IMAGE_ORDER_TYPE

From 
PAT_ENC ENC
Inner Join PATIENT on ENC.PAT_ID=PATIENT.PAT_ID
Inner Join CLARITY_DEP DEP on ENC.DEPARTMENT_ID=DEP.DEPARTMENT_ID
Left Join ZC_DISP_ENC_TYPE ZCEnc on ENC.ENC_TYPE_C=ZCEnc.DISP_ENC_TYPE_C
Left Join (Select PAT_ENC_CSN_ID, DESCRIPTION, ZC_ORDER_TYPE.NAME as ORDER_TYPE, PROC_CODE
				From ORDER_PROC
				Left Join ZC_ORDER_TYPE on ORDER_PROC.ORDER_TYPE_C=ZC_ORDER_TYPE.ORDER_TYPE_C
				Where ZC_ORDER_TYPE.NAME in any ('Digital Imaging','Imaging')) as IMAGE
				on ENC.PAT_ENC_CSN_ID=IMAGE.PAT_ENC_CSN_ID
Inner Join (Select PAT_ENC_CSN_ID, DESCRIPTION, PROC_CODE, ZC_RFL_CLASS.NAME as REF_TYPE
				From ORDER_PROC
				Inner Join ZC_RFL_CLASS on ZC_RFL_CLASS.RFL_CLASS_C = ORDER_PROC.RFL_CLASS_C
				--Where Clause = Internal Wound Care Referrals
				Where DESCRIPTION like '%REFERRAL WOUND CARE%'
				And ORDER_PROC.RFL_CLASS_C='1') as WOUND
				on ENC.PAT_ENC_CSN_ID=WOUND.PAT_ENC_CSN_ID
Where 
ENC.CONTACT_DATE> {d '2014-01-01'}
