Select AVA.DEPARTMENT_ID, AVB.DEPARTMENT_ID, AVA.PAT_ID, AVB.PAT_ID, AVA.PROV_ID, AVB.PROV_ID, AVA.SLOT_BEGIN_TIME, AVB.SLOT_BEGIN_TIME, AVA.APPT_NUMBER, AVB.APPT_NUMBER, AVB.NUM_APTS_SCHEDULED, AVA.APPT_PRC_ID, AVB.APPT_PRC_ID, AVA.NAME, AVB.NAME
From (Select DEPARTMENT_ID, PROV_ID,PAT_ID, SLOT_BEGIN_TIME, APPT_NUMBER, APPT_PRC_ID, AVAILABILITY.APPT_BLOCK_C, NAME
			From AVAILABILITY 
			Left Outer Join ZC_APPT_BLOCK 
			on AVAILABILITY.APPT_BLOCK_C=ZC_APPT_BLOCK.APPT_BLOCK_C
			Where APPT_NUMBER='0') as AVA
Inner Join (Select DEPARTMENT_ID, PROV_ID, PAT_ID, SLOT_BEGIN_TIME, APPT_NUMBER, APPT_PRC_ID, AVAILABILITY.APPT_BLOCK_C, NAME, NUM_APTS_SCHEDULED
					From AVAILABILITY
					Inner Join ZC_APPT_BLOCK
					on AVAILABILITY.APPT_BLOCK_C=ZC_APPT_BLOCK.APPT_BLOCK_C
					Where APPT_NUMBER<>'0') as AVB
		on AVA.DEPARTMENT_ID=AVB.DEPARTMENT_ID
		and AVA.PROV_ID=AVB.PROV_ID
		and AVA.SLOT_BEGIN_TIME=AVB.SLOT_BEGIN_TIME
		Where Cast(AVA.SLOT_BEGIN_TIME as date)> '2013-06-03'
Group By (1,2,3,4,5,6,7,8,9,10,11,12,13,14,15)
Order By AVB.SLOT_BEGIN_TIME, AVB.DEPARTMENT_ID