Select AVA.DEPARTMENT_ID,
AVA.DEPARTMENT_NAME,
AVA.PROV_ID, 
AVA.PROV_NAME, 
AVA.SLOT_BEGIN_TIME, 
AVA.APPT_NUMBER,
AVA.UNAVAILABLE_RSN_C, 
AVA.SLOT_LENGTH, 
AVA.ORG_REG_OPENINGS
From (Select AVAILABILITY.DEPARTMENT_ID, DEPARTMENT_NAME, AVAILABILITY.PROV_ID, PROV_NAME, PAT_ID, SLOT_BEGIN_TIME, APPT_NUMBER, APPT_PRC_ID, AVAILABILITY.APPT_BLOCK_C, NAME, UNAVAILABLE_RSN_C, SLOT_LENGTH, ORG_REG_OPENINGS, NUM_APTS_SCHEDULED
			From AVAILABILITY 
			Left Outer Join ZC_APPT_BLOCK 
			on AVAILABILITY.APPT_BLOCK_C=ZC_APPT_BLOCK.APPT_BLOCK_C
			Left Join CLARITY_DEP 
			on CLARITY_DEP.DEPARTMENT_ID=AVAILABILITY.DEPARTMENT_ID
			Left Join CLARITY_SER
			on CLARITY_SER.PROV_ID=AVAILABILITY.PROV_ID
			Where APPT_NUMBER='0') as AVA --SLOTS
Left Join (Select DEPARTMENT_ID, PROV_ID, PAT_ID, SLOT_BEGIN_TIME, APPT_NUMBER, APPT_PRC_ID, AVAILABILITY.APPT_BLOCK_C, NAME, NUM_APTS_SCHEDULED, SLOT_LENGTH, ORG_REG_OPENINGS
					From AVAILABILITY
					Inner Join ZC_APPT_BLOCK
					on AVAILABILITY.APPT_BLOCK_C=ZC_APPT_BLOCK.APPT_BLOCK_C
					Where APPT_NUMBER<>'0') as AVB --APPOINTMENTS
		on AVA.DEPARTMENT_ID=AVB.DEPARTMENT_ID
		and AVA.PROV_ID=AVB.PROV_ID
		and AVA.SLOT_BEGIN_TIME=AVB.SLOT_BEGIN_TIME
Where 
AVB.SLOT_BEGIN_TIME is null
And CAST(AVA.SLOT_BEGIN_TIME as DATE)= '2013-10-25'
And AVA.UNAVAILABLE_RSN_C is null
And AVA.DEPARTMENT_NAME  In  ('MH HLAK','MH REG','MH RDG','PSYCHIATRY HLAK','PSYCHIATRY RDG','PSYCHIATRY REG')
And AVA.NUM_APTS_SCHEDULED = '0'
And AVA.SLOT_LENGTH  In ('30','60')
And AVA.ORG_REG_OPENINGS >'0'
Order By AVA.DEPARTMENT_ID, AVA.PROV_ID, AVA.SLOT_BEGIN_TIME