Select Distinct
PLAN_GRP.PLAN_GRP_ID, 
PLAN_GRP.PLAN_GRP_NAME, 
CLARITY_EPP.BENEFIT_PLAN_ID,
CL_CMK.BENEFIT_PACKAGE_ID,
COMPON_GRP_LIST_ID,
ADJ_TABLE_CML_ID,
CL_CMG.COMPONENT_GRP_ID,
CL_CMG_CRITERIA.DX_COMPONENT_ID,
ZC_SD_RX_IN_OUT.NAME as DX_COMPON_IO,
CL_CMP.COMPONENT_ID,
CL_CMP_DESC.DESCRIPT as COMPONENT_DESC, --CMP 50 (CMP 40 is not ETLed)
CL_CMP_RANGE.RANGE_BEG,
CL_CMP_RANGE.RANGE_END

From
PLAN_GRP 
Inner Join PLAN_GRP_BEN_PLAN on PLAN_GRP.PLAN_GRP_ID=PLAN_GRP_BEN_PLAN.PLAN_GRP_ID And PLAN_GRP_BEN_PLAN.ACTIVE_YN<>'N' --Only Active Ben Plans
Inner Join CLARITY_EPP on PLAN_GRP_BEN_PLAN.BEN_PLAN_ID=CLARITY_EPP.BENEFIT_PLAN_ID And (CLARITY_EPP.RECORD_STAT_EPP_C is null or CLARITY_EPP.RECORD_STAT_EPP_C='0') --Only Active EPP Records
Inner Join CLARITY_EPP_OT on CLARITY_EPP.BENEFIT_PLAN_ID=CLARITY_EPP_OT.BENEFIT_PLAN_ID And CLARITY_EPP_OT.IS_BEN_PKG_REL_YN='Y' --Indicated if the Benefit Package and its corresponding Limit and Payment Parameters are ready to be used
Inner Join CL_CMK on CLARITY_EPP_OT.BEN_PACKAGE_ID=CL_CMK.BENEFIT_PACKAGE_ID And CL_CMK.RECORD_STATUS_C is null --Only Active CMK Records
Inner Join CL_CMK_COMPON_GRP on CL_CMK_COMPON_GRP.BENEFIT_PACKAGE_ID=CL_CMK.BENEFIT_PACKAGE_ID
Inner Join CL_CMG on CL_CMK_COMPON_GRP.COMPON_GRP_LIST_ID=CL_CMG.COMPONENT_GRP_ID And CL_CMG.RECORD_STATUS_C is null --Only Active CMG Records
Inner Join CL_CMG_CRITERIA on CL_CMG_CRITERIA.COMPON_GRP_ID=CL_CMG.COMPONENT_GRP_ID
Inner Join ZC_SD_RX_IN_OUT on CL_CMG_CRITERIA.DX_COMPON_IO_C=ZC_SD_RX_IN_OUT.SD_RX_IN_OUT_C
Inner Join CL_CMP on CL_CMG_CRITERIA.DX_COMPONENT_ID=CL_CMP.COMPONENT_ID And CL_CMP.RECORD_STATE_NAME is null And CL_CMP.COMPON_TYPE_C='1' --Only Active, Diagnosis CMP records
Inner Join CL_CMP_DESC on CL_CMP.COMPONENT_ID=CL_CMP_DESC.COMPONENT_ID
Inner Join CL_CMP_RANGE on CL_CMP.COMPONENT_ID=CL_CMP_RANGE.COMPONENT_ID

Where PLAN_GRP.ACTIVATION_DATE >= date '2012-01-01'