/*EDG_HX_MASTER TEST*/

--Find ICD-10 DX_ID's that have a count >1
Select *
From
(Select DX_ID, COUNT(*) as COUNTS
From HCCLCO5.EDG_HX_MASTER HX
Where ICD_VERSION_INDICATOR='ICD10'
Group By 1) as COUNTS
Where COUNTS.COUNTS>1;

--Compare the DX_ID's returned above to what is currently in EDG_HX_ICD10_LIST
Select *
From HCCLCO5.EDG_HX_MASTER HX
Left Join HCCLCO5.EDG_HX_ICD10_LIST LIST on HX.DX_ID=LIST.DX_ID and HX.EFF_START_DATE=LIST.EFF_START_DATE
Where ICD_VERSION_INDICATOR='ICD10'
And HX.DX_Id in any ('12145470',
'121140335',
'121140334');

--Search for any other ICD-10 DX_ID's where the EFF_START_DATE is 4/2/2014
Select *
From HCCLCO5.EDG_HX_MASTER HX
Where ICD_VERSION_INDICATOR='ICD10'
And CAST(EFF_START_DATE as DATE FORMAT 'YYYYMMDD')='20140402';

--Test Interpolated_Flag='1' where the EFF_START_DATE <> 1/1/1900
Select *
From HCCLCO5.EDG_HX_MASTER HX
Where INTERPOLATED_FLAG='1'
And CAST(EFF_START_DATE as DATE FORMAT 'YYYYMMDD')<>'19000101';


