SELECT
MYC_MESG.MESSAGE_ID,
CL_QFORM.FORM_ID, 
CL_QFORM.FORM_NAME,
MYC_MESG.CREATED_TIME, 
CL_QANSWER_QA.QUEST_ID, 
CASE When CL_QQUEST_OVTM.QUESTION is null then 'Total Score Q1 - Q9' Else CL_QQUEST_OVTM.QUESTION END as QUESTION,
CL_QANSWER.ANSWER_ID, 
CL_QANSWER_QA.QUEST_ANSWER,
PATIENT.PAT_MRN_ID,
ZC_SEX.NAME as PATIENT_GENDER,
CAST(((((MYC_MESG.CREATED_TIME(DATE))(INT))-((PATIENT.BIRTH_DATE(DATE))(INT))) *.0001) as SMALLINT) as PATIENT_AGE,

FROM MYC_MESG MYC_MESG
 Left Outer Join  MYC_MESG_QUESR_ANS MYC_MESG_QUESR_ANS on MYC_MESG_QUESR_ANS.MESSAGE_ID=MYC_MESG.MESSAGE_ID
 Left Outer Join CL_QANSWER CL_QANSWER on MYC_MESG_QUESR_ANS.QUESR_ANS_ID=CL_QANSWER.ANSWER_ID
 Left Outer Join PATIENT PATIENT on MYC_MESG.PAT_ID=PATIENT.PAT_ID
 Left Outer Join ZC_SEX ZC_SEX on PATIENT.SEX_C=ZC_SEX.RCPT_MEM_SEX_C
 Left Outer Join CL_QANSWER_QA CL_QANSWER_QA on CL_QANSWER.ANSWER_ID=CL_QANSWER_QA.ANSWER_ID
 Left Outer Join CL_QFORM CL_QFORM on CL_QANSWER.FORM_ID=CL_QFORM.FORM_ID
 Inner Join CL_QQUEST_OVTM CL_QQUEST_OVTM on (CL_QANSWER_QA.QUEST_DATE_REAL=CL_QQUEST_OVTM.CONTACT_DATE_REAL) and (CL_QANSWER_QA.QUEST_ID=CL_QQUEST_OVTM.QUEST_ID)
 Left Outer Join CL_QQUEST CL_QQUEST ON CL_QANSWER_QA.QUEST_ID=CL_QQUEST.QUEST_ID
 Left Outer Join ZC_MYC_MSG_TYP ZC_MES on ZC_MES.MYC_MSG_TYP_C=MYC_MESG.MYC_MSG_TYP_C

WHERE
FORM_NAME like '%PHQ-9%';


