SELECT Distinct
ID.PAT_ID,
ID.IDENTITY_ID as PAT_MRN_ID, 
PAT_ENC.PAT_ENC_CSN_ID,
PAT_ENC.CONTACT_DATE as PAT_ENC_CONTACT_DATE,
PROC.ORDERING_DATE as PROC_ORDERING_DATE,
PROC.PROC_CODE,
PROC.DESCRIPTION

FROM
ORDER_PROC as PROC
Inner Join PAT_ENC on PAT_ENC.PAT_ENC_CSN_ID=PROC.PAT_ENC_CSN_ID
Inner Join IDENTITY_ID as ID on PROC.PAT_ID=ID.PAT_ID

WHERE
PROC.PROC_CODE IN ('87230B','87324A','87493C','87493B') --C DIFF PROCS
and (PROC.ORDER_STATUS_C <> '4' 
		or PROC.ORDER_STATUS_C <> '9' ) --ELIMINATE CANCELLED AND DISCOUNTINUED ORDERS
and (PROC.ORDERING_DATE >= DATE'2012-01-01'
		and PROC.ORDERING_DATE <= DATE'2012-12-31') --ALL 2012 ORDERS
and PROC.PAT_ID not in (Select Distinct PAT_ID From PATIENT_TYPE Where PATIENT_TYPE_C='1214') --TEST PATIENT ELIMINATION
and ID.IDENTITY_ID='412846528' --MRN FOR EXAMPLE PATIENT

ORDER BY
PROC.PAT_ID, PROC.ORDERING_DATE

