Select Distinct
PAT_ENC.PAT_ID,
PAT_ENC.PAT_ENC_CSN_ID,
ZC.NAME as ENC_TYPE, 
DEP.DEPARTMENT_NAME,
PAT_ENC.AGE,
PAT_ENC.CONTACT_DATE,
ALG.ALRG_UPDT_DATE,
EMP.NAME as EMP_REVIEW_ALLERGY,
FLO.RECORD_DATE as BP_TAKEN_DATE,
FLO.FSD_ENTERED_BY as BP_ENTERED_BY,
FLO2.RECORD_DATE as WEIGHT_TAKEN_DATE,
FLO2.FSD_ENTERED_BY as WEIGHT_ENTERED_BY
From PAT_ENC
Inner Join ZC_DISP_ENC_TYPE ZC on PAT_ENC.ENC_TYPE_C=ZC.DISP_ENC_TYPE_C
Left Join PATIENT_ALG_UPD_HX ALG on PAT_ENC.PAT_ID=ALG.PAT_ID and PAT_ENC.CONTACT_DATE=ALG.ALRG_UPDT_DATE
Left Join CLARITY_EMP EMP on ALG.ALRG_UPDT_USER_ID=EMP.USER_ID
Left Join CLARITY_DEP DEP on PAT_ENC.DEPARTMENT_ID=DEP.DEPARTMENT_ID
Left Join (Select FLW_REC.PAT_ID, FLW_REC.RECORD_DATE, GP_DATA.FLO_DIS_NAME,  FLW_MEAS.FSD_ID, EMP.NAME as FSD_ENTERED_BY
				From IP_FLWSHT_REC FLW_REC 
				Inner Join IP_FLWSHT_MEAS FLW_MEAS on FLW_MEAS.FSD_ID=FLW_REC.FSD_ID
				Inner Join IP_FLO_GP_DATA GP_DATA on GP_DATA.FLO_MEAS_ID=FLW_MEAS.FLO_MEAS_ID
				Inner Join CLARITY_EMP EMP on FLW_MEAS.ENTRY_USER_ID=EMP.USER_ID
				Where GP_DATA.FLO_DIS_NAME ='BP'
			) as FLO on FLO.PAT_ID=PAT_ENC.PAT_ID and FLO.RECORD_DATE=PAT_ENC.CONTACT_DATE 
Left Join (Select FLW_REC.PAT_ID, FLW_REC.RECORD_DATE, GP_DATA.FLO_DIS_NAME,  FLW_MEAS.FSD_ID, EMP.NAME as FSD_ENTERED_BY
				From IP_FLWSHT_REC FLW_REC 
				Inner Join IP_FLWSHT_MEAS FLW_MEAS on FLW_MEAS.FSD_ID=FLW_REC.FSD_ID
				Inner Join IP_FLO_GP_DATA GP_DATA on GP_DATA.FLO_MEAS_ID=FLW_MEAS.FLO_MEAS_ID
				Inner Join CLARITY_EMP EMP on FLW_MEAS.ENTRY_USER_ID=EMP.USER_ID
				Where GP_DATA.FLO_DIS_NAME ='Weight'
			) as FLO2 on FLO2.PAT_ID=PAT_ENC.PAT_ID and FLO2.RECORD_DATE=PAT_ENC.CONTACT_DATE 
Where PAT_ENC.ENC_TYPE_C='101' --Office Visists
And CONTACT_DATE > date '2014-06-01'
And ENC_CLOSED_YN='Y' --Closed Encounters
And PAT_ENC.PAT_ID not in (Select PAT_ID From PATIENT_TYPE Where PATIENT_TYPE_C='1214') --Eliminate Test Patients