SELECT
ENC.PAT_ID,
ENC.CONTACT_DATE,
PATIENT.PAT_MRN_ID,
PROB.DX_ID, 
EDG.DX_NAME,
PROB.NOTED_DATE as PROBLEM_NOTED_DATE, 
PROB.RESOLVED_DATE as PROBLEM_RESOLVED_DATE, 
PROB.DATE_OF_ENTRY as PROBLEM_DATE_OF_ENTRY,
PROB.ENTRY_USER_ID, 
ZC2.NAME as PROBLEM_STATUS, --1: Active 2: Resolved 3: Deleted
PROB.UPDATE_DATE as PROBLEM_UPDATE_DATE, 
PROB.CHRONIC_YN, 
PROB.SHOW_IN_MYC_YN,
PROBHX.PROBLEM_LIST_ID as PROBLEM_LIST_ID_HX,
PROBHX.LINE as LINE_HX, 
PROBHX.HX_PROBLEM_ID,
EDGHX.DX_NAME as DX_HX_NAME,
PROBHX.HX_DATE_NOTED, 
PROB.OVERVIEW_NOTE_ID as PROBLEM_NOTE_ID,
HNO.NOTE_ID,
HNO.NOTE_DESC,
IP_NOTE_TYPE_C as NOTE_TYPE, 
HNO_NOTE_TEXT.CONTACT_DATE as NOTE_CONTACT_DATE,
HNO_NOTE_TEXT.NOTE_TEXT as HNO_NOTE_TEXT

FROM
PAT_ENC ENC
Inner Join PATIENT on PATIENT.PAT_ID=ENC.PAT_ID
Inner Join PROBLEM_LIST PROB on PROB.PROBLEM_EPT_CSN=ENC.PAT_ENC_CSN_ID
Left Join PROBLEM_LIST_HX PROBHX on PROBHX.HX_PROBLEM_EPT_CSN=ENC.PAT_ENC_CSN_ID
Inner Join CLARITY_EDG EDG on EDG.DX_ID=PROB.DX_ID
Inner Join CLARITY_EDG EDGHX on EDGHX.DX_ID=PROBHX.HX_PROBLEM_ID
Inner Join HNO_INFO HNO on ENC.PAT_ENC_CSN_ID=HNO.PAT_ENC_CSN_ID
Inner Join ZC_NOTE_TYPE_IP ZC1 ON HNO.IP_NOTE_TYPE_C = ZC1.TYPE_IP_C 
Left Join HNO_ENC_INFO INFO on INFO.NOTE_ID=HNO.NOTE_ID
Left Join HNO_NOTE_TEXT  on HNO.NOTE_ID=HNO_NOTE_TEXT.NOTE_ID
Inner Join ZC_PROBLEM_STATUS ZC2 on ZC2.PROBLEM_STATUS_C=PROB.PROBLEM_STATUS_C

WHERE
PATIENT.PAT_MRN_ID = any ('424203780','420317830','428193449','424203780','420070046')
and PROB.PROBLEM_LIST_ID is not null
and EDG.DX_NAME like '%AIDS%'
and DX_HX_NAME like '%AIDS%'
and HNO_NOTE_TEXT like '%AIDS%'
