Select 
PEND.REFERRAL_ID,
PEND.EXTERNAL_ID_NUM,
P.PAT_MRN_ID,
POOL.CHANGE_TYPE_C as POOL_CHANGE_TYPE,
POOL.Change_Type as POOL_CHANGE_TYPE_DESC,
PEND.CHANGE_TYPE_C as PEND_CHANGE_TYPE,
PEND.Change_Type as PEND_CHANGE_TYPE_DESC,
POOL. Current_Status,
MIN(POOL.CHANGE_DATETIME) AS Datetime_of_Pool_Entry,
IBM.IBM_Create AS Open_Ref_Req_To_Process,
PEND.ENTRY_DATE,
PEND.EXT_REF_DATE,
PEND.EMPLOYEE,
PEND.Reffered_by_Dept,
POOL.Reffered_to_Dept,
IBM.RegName AS Pool

From
(Select Distinct 
rh.REFERRAL_ID
	,ref.PAT_ID
	,ref.EXTERNAL_ID_NUM
	,rh.CHANGE_TYPE_C
	,zct.NAME AS Change_Type
	,zrs.NAME AS Current_Status
	,rh.CHANGE_DATETIME
	,ref.ENTRY_DATE
	,ref.EXT_REF_DATE
	,cep.NAME AS Employee
	,cde.DEPARTMENT_NAME AS Reffered_by_Dept
	,cde2.DEPARTMENT_NAME AS Reffered_to_Dept
FROM
REFERRAL REF
LEFT JOIN REFERRAL_HIST rh ON ref.REFERRAL_ID = rh.REFERRAL_ID
	LEFT JOIN ZC_RFL_STATUS zrs ON ref.RFL_STATUS_C = zrs.RFL_STATUS_C 
	LEFT JOIN ZC_RFL_HST_CHG_TYP zct ON rh.CHANGE_TYPE_C = zct.CHANGE_TYPE_C
	LEFT JOIN CLARITY_EMP cep ON rh.CHANGE_USER_ID = cep.USER_ID
	LEFT JOIN CLARITY_DEP cde ON ref.REFD_BY_DEPT_ID = cde.DEPARTMENT_ID 
	LEFT JOIN CLARITY_DEP cde2 ON ref.REFD_TO_DEPT_ID = cde2.DEPARTMENT_ID 
WHERE 
ref.PAT_ID NOT IN (SELECT DISTINCT PAT_ID FROM PATIENT_TYPE WHERE PATIENT_TYPE_C = 1214) --KP Test pt elimination
AND ref.RFL_CLASS_C = '3' --Limits to just Outgoing message
AND rh.CHANGE_TYPE_C = '39') as POOL

Left Join 
(Select Distinct 
rh.REFERRAL_ID
	,ref.PAT_ID
	,ref.EXTERNAL_ID_NUM
	,rh.CHANGE_TYPE_C
	,zct.NAME AS Change_Type
	,zrs.NAME AS Current_Status
	,rh.CHANGE_DATETIME
	,ref.ENTRY_DATE
	,ref.EXT_REF_DATE
	,cep.NAME AS Employee
	,cde.DEPARTMENT_NAME AS Reffered_by_Dept
	,cde2.DEPARTMENT_NAME AS Reffered_to_Dept
FROM
REFERRAL REF
LEFT JOIN REFERRAL_HIST rh ON ref.REFERRAL_ID = rh.REFERRAL_ID
	LEFT JOIN ZC_RFL_STATUS zrs ON ref.RFL_STATUS_C = zrs.RFL_STATUS_C 
	LEFT JOIN ZC_RFL_HST_CHG_TYP zct ON rh.CHANGE_TYPE_C = zct.CHANGE_TYPE_C
	LEFT JOIN CLARITY_EMP cep ON rh.CHANGE_USER_ID = cep.USER_ID
	LEFT JOIN CLARITY_DEP cde ON ref.REFD_BY_DEPT_ID = cde.DEPARTMENT_ID 
	LEFT JOIN CLARITY_DEP cde2 ON ref.REFD_TO_DEPT_ID = cde2.DEPARTMENT_ID 
WHERE 
ref.PAT_ID NOT IN (SELECT DISTINCT PAT_ID FROM PATIENT_TYPE WHERE PATIENT_TYPE_C = 1214) --KP Test pt elimination
AND ref.RFL_CLASS_C = '3' --Limits to just Outgoing message
AND rh.CHANGE_TYPE_C in any ('4','7')) as PEND
on POOL.REFERRAL_ID=PEND.REFERRAL_ID
and POOL.PAT_ID=PEND.PAT_ID

INNER JOIN
	(SELECT ib.REFERRAL_ID AS RefID 
	,ib.CREATE_TIME AS IBM_Create 
	,ch.REGISTRY_ID AS RegId 
	,ch.REGISTRY_NAME AS RegName
		FROM IB_MESSAGES ib 
		LEFT JOIN CLARITY_HIP ch 
		ON ib.SENDER_REGISTRY = ch.REGISTRY_ID
		WHERE ch.REGISTRY_ID 
		IN ('140392', '140517', '140204', '140341',  '14020572', '140175')) AS IBM  ON PEND.REFERRAL_ID = IBM.RefID
LEFT JOIN PATIENT p ON PEND.PAT_ID = p.PAT_ID

GROUP BY
PEND.REFERRAL_ID,
PEND.EXTERNAL_ID_NUM,
P.PAT_MRN_ID,
PEND.CHANGE_TYPE_C,
PEND.Change_Type,
POOL.CHANGE_TYPE_C,
POOL.Change_Type,
POOL. Current_Status,
POOL.CHANGE_DATETIME,
IBM.IBM_Create,
PEND.ENTRY_DATE,
PEND.EXT_REF_DATE,
PEND.EMPLOYEE,
PEND.Reffered_by_Dept,
POOL.Reffered_to_Dept,
IBM.RegName

Where
CAST(POOL.ENTRY_DATE as DATE) > '2013-07-17'

ORDER BY
PEND.REFERRAL_ID,
PEND.CHANGE_TYPE_C