--Niks Query with Jordan's Tables
Select 
MAX_SLOT_TIME as SLOT_BEGIN_DT, 
TEMPLATE_DATE,
RELEASE_DATE,
PROV_NAME as PROVIDER_NAME, 
PROV_TYPE,
SLOT_NAME,
LOC_NAME,
SPECIALTY,
CAST(MAX_SLOT_TIME as DATE) - CURRENT_DATE as DAYS_OUT

From (Select 
LOC.LOC_NAME,
DEP.SPECIALTY,
SER.PROV_NAME,
SER.PROV_TYPE,
TEMPLATE_DATE,
RELEASE_DATE,
ZCAPPT.NAME as SLOT_NAME,
MAX(AVAIL.SLOT_BEGIN_TIME) as MAX_SLOT_TIME
From AVAILABILITY AVAIL
Inner Join CLARITY_DEP DEP on AVAIL.DEPARTMENT_ID=DEP.DEPARTMENT_ID
Inner Join CLARITY_LOC LOC on DEP.REV_LOC_ID=LOC.LOC_ID
Inner Join CLARITY_SER SER on SER.PROV_ID=AVAIL.PROV_ID
Inner Join AVAIL_BLOCK BLOCK on AVAIL.DEPARTMENT_ID=BLOCK.DEPARTMENT_ID
														and AVAIL.SLOT_BEGIN_TIME=BLOCK.SLOT_BEGIN_TIME
														and AVAIL.PROV_ID=BLOCK.PROV_ID
Left Join ZC_APPT_BLOCK ZCAPPT on BLOCK.BLOCK_C=ZCAPPT.APPT_BLOCK_C
Left Join (Select Distinct ES_SCHED_TEMPLATE.DEPARTMENT_ID, ES_SCHED_TEMPLATE.PROV_ID, MAX(END_DATE_TIME_RANGE) as TEMPLATE_DATE, RELEASE_DATE
				From ES_SCHED_TEMPLATE 
				Left Join TEMPLATE on ES_SCHED_TEMPLATE.PROV_ID=TEMPLATE.PROV_ID and ES_SCHED_TEMPLATE.DEPARTMENT_ID=TEMPLATE.DEPARTMENT_ID
				Where END_DATE_TIME_RANGE > date '2014-05-01'
				And RELEASE_DATE > date '2014-05-01'
				Group by 1,2,4) as ES_TEMP
				on AVAIL.DEPARTMENT_ID=ES_TEMP.DEPARTMENT_ID and AVAIL.PROV_ID=ES_TEMP.PROV_ID

Where LOC.LOC_NAME in any ('FRANKLIN MEDICAL OFFICES'
											/*'ARAPAHOE MEDICAL OFFICES','AURORA CENTREPOINT MED OFFICES','BASELINE MEDICAL OFFICES',
											'BRIARGATE SENIOR HEALTH CENTER','BRIGHTON MEDICAL OFFICES','CASTLE ROCK MEDICAL OFFICES',
											'EAST DENVER MEDICAL OFFICES','ENGLEWOOD MEDICAL OFFICES','EVERGREEN MEDICAL OFFICES',
											'FT.COLLINS MEDICAL OFFICES','GREELEY MOB','HIDDEN LAKE MEDICAL OFFICES',
											'HIGHLANDS RANCH MEDICAL OFFICE','KEN CARYL MEDICAL OFFICE','LAKEWOOD MEDICAL OFFICES',
											'LONE TREE MEDICAL OFFICES','LONGMONT MEDICAL OFFICES','LOVELAND MEDICAL OFFICES',
											'PARKER MEDICAL OFFICES','PUEBLO NORTH MEDICAL OFFICES','REGIONAL OFFICES','RIDGELINE BEHAVIORAL HEALTH',
											'ROCK CREEK MEDICAL OFFICES','SKYLINE MEDICAL OFFICES','SMOKY HILL MEDICAL OFFICES','SOUTHWEST MEDICAL OFFICES',
											'WESTMINSTER MEDICAL OFFICES','WHEAT RIDGE MEDICAL OFFICES'*/)
And APPT_NUMBER='0'
And SER.PROV_ID in any ('14044000825','12110110106','1401020','15011938') --PROV_ID
Group By (1,2,3,4,5,6,7)) as SLOT
Where DAYS_OUT >= '0'
Order By SLOT.LOC_NAME ASC, SLOT.SPECIALTY ASC;

---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
--Steve's Query with Jordan's Tables
Select 
MAX_SLOT_TIME as SLOT_BEGIN_DT, 
TEMPLATE_DATE,
RELEASE_DATE,
PROV_NAME as PROVIDER_NAME, 
PROV_TYPE,
SLOT_NAME,
LOC_NAME,
SPECIALTY,
CAST(MAX_SLOT_TIME as DATE) - CURRENT_DATE as DAYS_OUT

From (Select 
LOC.LOC_NAME,
DEP.SPECIALTY,
SER.PROV_NAME,
SER.PROV_TYPE,
TEMPLATE_DATE,
RELEASE_DATE,
ZCAPPT.NAME as SLOT_NAME,
MAX(AVAIL.SLOT_BEGIN_TIME) as MAX_SLOT_TIME
From AVAILABILITY AVAIL
Inner Join CLARITY_DEP DEP on AVAIL.DEPARTMENT_ID=DEP.DEPARTMENT_ID
Inner Join CLARITY_LOC LOC on DEP.REV_LOC_ID=LOC.LOC_ID
Inner Join CLARITY_SER SER on SER.PROV_ID=AVAIL.PROV_ID
Inner Join AVAIL_BLOCK BLOCK on AVAIL.DEPARTMENT_ID=BLOCK.DEPARTMENT_ID
														and AVAIL.SLOT_BEGIN_TIME=BLOCK.SLOT_BEGIN_TIME
														and AVAIL.PROV_ID=BLOCK.PROV_ID
Left Join ZC_APPT_BLOCK ZCAPPT on BLOCK.BLOCK_C=ZCAPPT.APPT_BLOCK_C
Left Join (Select Distinct ES_SCHED_TEMPLATE.DEPARTMENT_ID, ES_SCHED_TEMPLATE.PROV_ID, MAX(END_DATE_TIME_RANGE) as TEMPLATE_DATE, RELEASE_DATE
				From ES_SCHED_TEMPLATE 
				Left Join TEMPLATE on ES_SCHED_TEMPLATE.PROV_ID=TEMPLATE.PROV_ID and ES_SCHED_TEMPLATE.DEPARTMENT_ID=TEMPLATE.DEPARTMENT_ID
				Where END_DATE_TIME_RANGE > date '2014-05-01'
				And RELEASE_DATE > date '2014-05-01'
				Group by 1,2,4) as ES_TEMP
				on AVAIL.DEPARTMENT_ID=ES_TEMP.DEPARTMENT_ID and AVAIL.PROV_ID=ES_TEMP.PROV_ID

Where LOC.LOC_NAME in any ('FRANKLIN MEDICAL OFFICES'
											/*'ARAPAHOE MEDICAL OFFICES','AURORA CENTREPOINT MED OFFICES','BASELINE MEDICAL OFFICES',
											'BRIARGATE SENIOR HEALTH CENTER','BRIGHTON MEDICAL OFFICES','CASTLE ROCK MEDICAL OFFICES',
											'EAST DENVER MEDICAL OFFICES','ENGLEWOOD MEDICAL OFFICES','EVERGREEN MEDICAL OFFICES',
											'FT.COLLINS MEDICAL OFFICES','GREELEY MOB','HIDDEN LAKE MEDICAL OFFICES',
											'HIGHLANDS RANCH MEDICAL OFFICE','KEN CARYL MEDICAL OFFICE','LAKEWOOD MEDICAL OFFICES',
											'LONE TREE MEDICAL OFFICES','LONGMONT MEDICAL OFFICES','LOVELAND MEDICAL OFFICES',
											'PARKER MEDICAL OFFICES','PUEBLO NORTH MEDICAL OFFICES','REGIONAL OFFICES','RIDGELINE BEHAVIORAL HEALTH',
											'ROCK CREEK MEDICAL OFFICES','SKYLINE MEDICAL OFFICES','SMOKY HILL MEDICAL OFFICES','SOUTHWEST MEDICAL OFFICES',
											'WESTMINSTER MEDICAL OFFICES','WHEAT RIDGE MEDICAL OFFICES'*/)
And APPT_NUMBER='0'
------
And TIME_HELD_YN = 'N'
And DAY_HELD_YN = 'N'
And TIME_UNAVAIL_YN = 'N'
And DAY_UNAVAIL_YN = 'N'
------
And SER.PROV_ID in any ('14044000825','12110110106','1401020','15011938') --PROV_ID
Group By (1,2,3,4,5,6,7)) as SLOT
Where DAYS_OUT >= '0'
Order By SLOT.LOC_NAME ASC, SLOT.SPECIALTY ASC;