--What Question Form_ID do you need?
Select *
From CL_QFORM
Where FORM_NAME like '%CARDIAC REHAB%';

--IVR Patients
SELECT DISTINCT
QFQ.FORM_ID, 
QQ.QUEST_ID, 
QQ.QUEST_NAME, 
PAT.PAT_MRN_ID, 
PAT.PAT_ID, 
PAT.PAT_NAME, 
QOVTM.QUESTION, 
PAT.QUEST_ANSWER, 
PAT.CONTACT_DATE

FROM
CL_QQUEST QQ
Left Join CL_QQUEST_OVTM QOVTM on QOVTM.QUEST_ID=QQ.QUEST_ID
Left Join CL_QFORM_QUEST QFQ on QFQ.QUEST_ID=QQ.QUEST_ID
Left Join CL_QQUEST_QFRESP QF on QF.QUESTION_ID=QQ.QUEST_ID
Inner Join (Select PAT_ENC_QUESR.CONTACT_DATE, PATIENT.PAT_ID, PATIENT.PAT_NAME, PATIENT.BIRTH_DATE, PATIENT.SEX, PATIENT.PAT_MRN_ID, PAT_ENC_QUESR.QUEST_ID, PAT_ENC_QUESR.QUEST_DATE, PAT_ENC_QUESR.QUEST_ANSWER
     From PATIENT 
     Inner Join PAT_ENC_QUESR
     on PAT_ENC_QUESR.PAT_ID=PATIENT.PAT_ID) as PAT on PAT.QUEST_ID=QQ.QUEST_ID

WHERE
QFQ.FORM_ID= '1401054'
And QOVTM.Contact_Date=(Select Max(Contact_Date) as Contact_Date
            From CL_QQUEST_OVTM OVTM
            Where OVTM.Quest_ID=QOVTM.Quest_ID)
--And PAT.CONTACT_DATE>'01/01/2013'
Group By (1,2,3,4,5,6,7,8,9);



--My Chart
SELECT DISTINCT
PAT.PAT_MRN_ID,
PAT.PAT_NAME,
ANS.LINE,
MES.CREATED_TIME,
QFORM.FORM_ID,
FORM_NAME, 
QUEST.QUEST_ID,
QUEST.QUESTION,
QA.QUEST_ANSWER

FROM
MYC_MESG_QUESR_ANS ANS
Inner Join MYC_MESG MES on ANS.MESSAGE_ID=MES.MESSAGE_ID --KP MESSAGE INFO
Left Join PATIENT PAT on MES.PAT_ID=PAT.PAT_ID
Left Join CL_QANSWER_QA QA on QA.ANSWER_ID=ANS.QUESR_ANS_ID --ANSWER TEXT
Left Join (Select a.QUEST_ID, a.QUESTION 
					from CL_QQUEST_OVTM a		
                    inner join (select QUEST_ID, max(CONTACT_DATE_REAL) as MAX_CONTACT_DATE from CL_QQUEST_OVTM group by 1) MAX_QUEST 		
                    on a.QUEST_ID = MAX_QUEST.QUEST_ID and a.CONTACT_DATE_REAL = MAX_QUEST.MAX_CONTACT_DATE) as QUEST--QUEST TEXT
     on QUEST.QUEST_ID=QA.QUEST_ID
Inner Join CL_QFORM_QUEST FORM_QUEST on QUEST.QUEST_ID=FORM_QUEST.QUEST_ID
Inner Join CL_QFORM QFORM on  FORM_QUEST.FORM_ID = QFORM.FORM_ID

ORDER BY
QA.ANSWER_ID,
QA.LINE

WHERE
FORM_QUEST.FORM_ID= '1401054'
--and MES.CREATED_TIME>'2013-01-01 00:00:00'
;
