SELECT DISTINCT 
CAST(ENC.APPT_TIME as DATE),
DEP.DEPARTMENT_NAME,
SER.PROV_NAME,
PATIENT.PAT_MRN_ID,
PATIENT.PAT_FIRST_NAME,
PATIENT.PAT_LAST_NAME,
EMP.NAME,
DEP.DEPARTMENT_NAME,
ENC.AGE,
PRC.PRC_NAME

FROM
PAT_ENC ENC
Left Join CLARITY_DEP DEP on ENC.DEPARTMENT_ID=DEP.DEPARTMENT_ID
Left Join CLARITY_PRC PRC on ENC.APPT_PRC_ID=PRC.PRC_ID
Left Join PATIENT on PATIENT.PAT_ID=ENC.PAT_ID
Left Join CLARITY_SER SER on SER.PROV_ID=ENC.VISIT_PROV_ID
Left Join CLARITY_EMP EMP on EMP.LGIN_DEPARTMENT_ID=DEP.DEPARTMENT_ID

WHERE
CAST(ENC.APPT_TIME as DATE)  >= '2013-08-01'
--and ENC.AGE >= '65'
and EMP.NAME <> any ( 'MIER, ROSA M','CHAGOLLA, DEBORAH L','MEINCKE, JENNIFER M','MONDRAGON, LISA M','GORDON, BARBARA A','PETERSON, ASHLEY N','RODRIGUEZ, AMANDA','VIGIL, TERRINA C','NORSLANDTER, NAOMI','HARSVICK, LYNDA M','STAMPS, JENNIFER L','WRIGHT, TAMMY A','DE LESTREE SHERRY, NADINE E','GARRETT, LINDA L','MONTOYA, CYNTHIA V','MCMILLEN, TAMARA','MONTOYA, CYNTHIA','CASAS-VIGIL, MARIA','SMILEY, SUSAN D','CHAGOLLA, DEBBIE L','MIER, ROSA M'  )
and ( PRC_ABBR ='kp.org-PHYS'
or PRC_ABBR ='KP.ORG PHYS'
or  PRC_ABBR = 'PhysConsult')